apiVersion: multen.dante-lor.github.io/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: multen-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  # TODO(user): Add fields here
